# Generated by Django 5.2.7 on 2025-11-01 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_service_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='cutomer',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['list_order'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='service',
        ),
        migrations.AddField(
            model_name='appointment',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='customer_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='customer_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='services',
            field=models.ManyToManyField(to='api.service'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='Confirmed', max_length=20),
        ),
        migrations.CreateModel(
            name='TechnicianAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.technician')),
            ],
            options={
                'verbose_name_plural': 'Technician Availabilities',
                'unique_together': {('technician', 'day_of_week')},
            },
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
