# Generated by Django 5.2.7 on 2025-11-01 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_appointment_cutomer_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('reason', models.CharField(blank=True, max_length=100, null=True)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.technician')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
